management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - info
          - metric
spring.cloud.stream:
  function:
    definition: tweetAnalyzer
  bindings:
    tweetAnalyzer-in-0:
      destination: tweets
  kafka:
    bindings:
      tweetAnalyzer-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
    binder:
      brokers:
        - 127.0.0.1:9092
